# MONGODB (MongoProperties)
spring:
  application:
    name: pet-store
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: pet-store
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration



server:
  port: 8081